language: erlang
otp_release:
  - "20.0"
  - "20.1"
  - "21.1"
  - "21.2"
  - "21.3"
  - "22.0"
matrix:
  allow_failures:
    - opt_release: "22.0"
  fast_finish: true

install:
  - rebar3 get-deps

script:
  - rebar3 travis
